### ISSUE TITLE
Almost working on Smartphone..

### ISSUE THREAD

**Issue by xekebet62** [drygdryg/OneShot#1]
Hi! I tried to run this script on my smartphone via wlan0 with NetHunter. I mean the internal chipset (not external wifi!).
The script works good, if I test it on the WiFi-AP to which I am already connected. But if I am not connected to this network (WiFi-AP), I get "Associated with AP... Scanning ... Associated with AP ... Scanning ...." again and again.
[Screenshot 1](https://a.radikal.ru/a19/1910/32/2d23f8489ef4.jpg) [Screenshot 2](https://d.radikal.ru/d07/1910/b7/f011858b10d2.jpg) 
Sorry for my bad English.

**Comment by drygdryg** [comment]
Отключали ли вы Wi-Fi перед тем как запускать скрипт? Попробуйте отключить Wi-Fi через настройки или шторку, после этого запустить скрипт. Либо отключить Wi-Fi, поднять интерфейс (`ip l set wlan0 up`) и после этого запустить OneShot.

English:
Did you disable Wi-Fi before running the tool? Try to disable Wi-Fi in Android settings, then run the OneShot. Either disable Wi-Fi, up the interface ('ip l set wlan0 up`) and then run OneShot.

**Comment by MrKira34** [comment]
Та же проблема, попробовал:

> Попробуйте отключить Wi-Fi через настройки или шторку, после этого запустить скрипт. Либо отключить Wi-Fi, поднять интерфейс (ip l set wlan0 up) и после этого запустить OneShot.

Проблема осталась. Устройство Xiaomi Redmi Note 8 Pro, root. Стоит Linux Deploy Alpine

**Comment by Namig09** [comment]
Как устанавливать?  Помогите пожалуйста. Писал git clone https://github.com/drygdryg/OneShot
А что дальше.

**Comment by drygdryg** [comment]
> Как устанавливать? Помогите пожалуйста. Писал git clone https://github.com/drygdryg/OneShot
> А что дальше.
Прочитайте README.md
