### ISSUE TITLE
Отчёт в формате RS

### ISSUE THREAD

**Issue by retro-desert** [drygdryg/OneShot#12]
Предлагаю сделать отчёт о полученных данных ( -w) в формате логов router scan'а, чтобы было удобно сразу отправлять.

**Comment by drygdryg** [comment]
Как вы себе это представляете?
Router Scan извлекает учётные данные из веб-интерфейса роутера, OneShot же получает только WPS PIN, пароль и ESSID; извлечь такие данные, как IP-адреса, "Server name / Realm name / Device type" не представляется возможным.
Если вам нужна удобная загрузка в 3WiFi, то, скорее, правильнее будет написать конвертер отчётов OneShot в таблицу CSV Router Scan.

**Comment by retro-desert** [comment]
Я говорю просто про пароль, wps pin, bssid, essid

**Comment by drygdryg** [comment]
Нет смысла использовать такой формат хранения отчётов в OneShot. Для вашей задачи разумно написать отдельный скрипт, который преобразует все файлы отчётов в одну таблицу Router Scan. Вот набросок: https://gist.github.com/drygdryg/f2404176683f5243235d8b0590c0730b

**Comment by retro-desert** [comment]
@drygdryg  Большое спасибо за ответ и за набросок. Я рассчитывал на такой ответ, но все же решил посоветоваться. Постараюсь довести до ума)
