### ISSUE TITLE
And how is that possible ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [drygdryg/OneShot#15]

**Comment by drygdryg** [comment]
**How Pixie Dust attack works**

OneShot runs wpa_supplicant like this:
`wpa_supplicant -K -d -Dnl80211,wext,hostapd,wired -i<interface> -c<config file>`
Then it connects to wpa_supplicant via its [control interface](https://www.w1.fi/wpa_supplicant/devel/ctrl_iface_page.html) and initializes the WPS connection, while capturing the wpa_supplicant log and extracting Pixiewps data from it.
After receiving the necessary data, the script passes it to Pixiewps and waits for the results; if the pin code is found, OneShot starts a new connection and extracts the network password from the wpa_supplicant log, then prints it to the screen.

**Comment by minanagehsalalma** [comment]
@drygdryg hmm if it is just possible like this then why they used to do it using monitor mode and made us think that's only possible with adapters that support monitor mode ?

**Comment by drygdryg** [comment]
@minanagehsalalma Actually, it's not that bad.There are tools for Windows that can perform Pixie Dust attack without monitor mode: [Router Scan](http://stascorp.com/load/1-1-0-56), [Waircut](https://sourceforge.net/projects/waircut/) (it was the first).

It seems to me that nothing similar has been done for Linux because many people who are involved in professional security audits have special equipment. But it didn't occur to anyone that someone would need to audit WPS from their smartphone, where the monitor mode is not available.

So rofl0r and I decided to fix this problem.

**Comment by minanagehsalalma** [comment]
> without monitor mode: [Router Scan](http://stascorp.com/load/1-1-0-56), [Waircut](https://sourceforge.net/projects/waircut/) (it was the first).

Waircut worked but i didn't seem to get router scan to work ..  the problem is with waircut that you can't add the ssid of hidden networks which makes no sense at all even i told the dev but he didn't implement it.



> their smartphone, where the monitor mode is not available.

You mean that this available for android too ? But it requires root , right?


> So rofl0r and I decided to fix this problem.

Yup you both did great work.

**Comment by drygdryg** [comment]
> Waircut worked but i didn't seem to get router scan to work

Then try Router Scan. It only requires [Npcap](https://nmap.org/npcap/).
> You mean that this available for android too ? But it requires root , right?

Yes, there are two installation methods available:
1) Using [Linux Deploy](https://play.google.com/store/apps/details?id=ru.meefik.linuxdeploy) and some Linux distro;
2) Using [Termux](https://play.google.com/store/apps/details?id=com.termux).

If you go second, you can build wpa_supplicant and Pixiewps [manually](https://github.com/drygdryg/OneShot#termux) or use [user-friendly installer](https://github.com/drygdryg/OneShot_Termux_installer) with pre-built binaries.
> I remember that wifiwarden app dev told me that android doesn't have enough power to perform this.

WiFi Warden app uses the Android system wpa_supplicant — OneShot works differently on Android: it requires non-modded external wpa_supplicant (installs independently in the Linux Deploy or Termux environment). OneShot works only when Wi-Fi is turned off in the system settings.

**Comment by minanagehsalalma** [comment]
> Then try Router Scan. It only requires [Npcap](https://nmap.org/npcap/)

Tried it just not like waircut



> Yes, there are two installation methods available:
> 
> 1. Using [Linux Deploy](https://play.google.com/store/apps/details?id=ru.meefik.linuxdeploy) and some Linux distro;
> 2. Using [Termux](https://play.google.com/store/apps/details?id=com.termux).
> 
> If you go second, you can build wpa_supplicant and Pixiewps [manually](https://github.com/drygdryg/OneShot#termux) or use [user-friendly installer](https://github.com/drygdryg/OneShot_Termux_installer) with pre-built binaries.

Then add it to the readme


> OneShot works only when Wi-Fi is turned off in the system settings.

Hmm is that even allowed on android?

**Comment by drygdryg** [comment]
> Hmm is that even allowed on android?

On most Android devices, the wlan0 interface remains available after Wi-Fi is disabled. To use it, you just need to up it:
`ip l set wlan0 up`

OneSh does this automatically.

**Comment by minanagehsalalma** [comment]
> the wlan0 interface remains available after Wi-Fi is disabled. To use it, you just need to up it:
> `ip l set wlan0 up`

Whoa this the first time i hear that.

So connecting to a wifi and creating a hotspot at the same time is possible right ? 
Is root required for that step ?

**Comment by drygdryg** [comment]
> So connecting to a wifi and creating a hotspot at the same time is possible right ?

I think this is not available. You can switch wlan0 to WDS mode only.

**Comment by minanagehsalalma** [comment]
That's a really great addition to android as linux have no real problem with monitor mode even with adapters that doesn't support it. 

The only problem was on android as monitor mode isn't mostly possible.

A video of it working on android would really be great :::

**Comment by drygdryg** [comment]
> A video of it working on android would really be great :::

If you have root, just try it. It won't take you more than 15 minutes.
I should warn you that the script does not work on some MediaTek-based devices; this is because when you disable Wi-Fi there, the wlan0 interface is deleted.

**Comment by minanagehsalalma** [comment]
> If you have root

Unfortunately i don't :::



> I should warn you that the script does not work on some MediaTek-based devices

No problem.
