### ISSUE TITLE
Проблема работы OneShot на Android 10 (Xiaomi Redmi Note 7)

### ISSUE THREAD

**Issue by fateev1000** [drygdryg/OneShot#22]
Обновил сегодня Xiaomi Redmi Note 7 до официальной MIUI на Android 10( до этого был Android 9) и OneShot перестал нормально работать. 
После отключения WIFI через шторку телефон не видит интерфейс wlan0.
Ввожу в Termux: 

sudo python pixiewps-master/oneshot.py -i wlan0 —iface-down -K -w

Termux пишет: 

Cannot find device "wlan0"
Unable to up interface "wlan0"

Если в шторке включить WIFI, то OneShot не ругается и сканирует, но при попытке подключения бесконечный цикл:

Select target ("r" for refresh): 2
[*] Running wpa_supplicant…
[*] Trying PIN '12345670'…
[*] Scanning…
[*] Scanning…
[*] Scanning…
[*] Scanning…
[*] Associating with AP…
[+] Associated with B0:4E:26:D0:14:94 (ESSID: TP-Link_1494)
[*] Scanning…
[*] Associating with AP…
[+] Associated with B0:4E:26:D0:14:94 (ESSID: TP-Link_1494)
[*] Scanning…
[*] Associating with AP…
[+] Associated with B0:4E:26:D0:14:94 (ESSID: TP-Link_1494)
[*] Scanning…
[*] Associating with AP…
[+] Associated with B0:4E:26:D0:14:94 (ESSID: TP-Link_1494)
[*] Scanning…
[*] Associating with AP…
[+] Associated with B0:4E:26:D0:14:94 (ESSID: TP-Link_1494)
[*] Scanning…
^C
Aborting…

При это если начать подключение через OneShot, то меня отключает от подключенного WIFI в самой системе и в OneShot бесконечный цикл.
При это каким-то чудом у меня один раз получилось запустить OneShot со включенным WIFI в шторке и он нормально подключился к точке через OneShot. Я тогда пробовал без —iface-down. Но это не закономерность. Второй раз у меня не получилось это сделать.
На Android 9 такой проблемы не было. Все работало как надо. При выключенном WIFI через шторку OneShot работал замечательно. Не хотелось бы откатываться на Android 9.... но если OneShot нельзя заставить работать на 10, то придется. Так как очень полезная штука.

**Comment by paradoxx816** [comment]
Посмотри интерфейсы через ifconfig, может поменялось имя (что вряд ли). Скорее всего просто слетел рут

**Comment by fateev1000** [comment]
Да рут слетела, но я его поставил заново. Рут есть.

При включенном WIFI:

$ sudo ifconfig
dummy0: flags=195<UP,BROADCAST,RUNNING,NOARP> mtu 1500
inet6 fe80::8068:21ff:fe3e:8a83 prefixlen 64 scopeid 0x20<link>
ether 82:68:21:3e:8a:83 txqueuelen 1000 (Ethernet)
RX packets 0 bytes 0 (0.0 B)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 264 bytes 37544 (36.6 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
inet 127.0.0.1 netmask 255.0.0.0
inet6 ::1 prefixlen 128 scopeid 0x10<host>
loop txqueuelen 1 (Local Loopback)
RX packets 209 bytes 15888 (15.5 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 209 bytes 15888 (15.5 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

rmnet_data0: flags=65<UP,RUNNING> mtu 2000
inet6 fe80::147a:255f:22ed:3948 prefixlen 64 scopeid 0x20<link>
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
RX packets 20 bytes 3307 (3.2 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 16 bytes 1179 (1.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

rmnet_ipa0: flags=65<UP,RUNNING> mtu 2000
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
RX packets 10 bytes 3547 (3.4 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 16 bytes 1179 (1.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet 192.168.0.101 netmask 255.255.255.0 broadcast 192.168.0.255
inet6 fe80::d29c:7aff:feed:2a37 prefixlen 64 scopeid 0x20<link>
ether d0:9c:7a:ed:2a:37 txqueuelen 3000 (Ethernet)
RX packets 728341 bytes 927379046 (884.4 MiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 401774 bytes 31421894 (29.9 MiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0


При выключенном WIFI

$ sudo ifconfig
dummy0: flags=195<UP,BROADCAST,RUNNING,NOARP> mtu 1500
inet6 fe80::8068:21ff:fe3e:8a83 prefixlen 64 scopeid 0x20<link>
ether 82:68:21:3e:8a:83 txqueuelen 1000 (Ethernet)
RX packets 0 bytes 0 (0.0 B)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 275 bytes 39074 (38.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
inet 127.0.0.1 netmask 255.0.0.0
inet6 ::1 prefixlen 128 scopeid 0x10<host>
loop txqueuelen 1 (Local Loopback)
RX packets 218 bytes 16653 (16.2 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 218 bytes 16653 (16.2 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

rmnet_data0: flags=65<UP,RUNNING> mtu 2000
inet6 fe80::147a:255f:22ed:3948 prefixlen 64 scopeid 0x20<link>
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
RX packets 20 bytes 3307 (3.2 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 16 bytes 1179 (1.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

rmnet_ipa0: flags=65<UP,RUNNING> mtu 2000
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
RX packets 10 bytes 3547 (3.4 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 16 bytes 1179 (1.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

**Comment by fateev1000** [comment]
> Посмотри интерфейсы через ifconfig, может поменялось имя (что вряд ли). Скорее всего просто слетел рут

Да рут слетела, но я его поставил заново. Рут есть.

При включенном WIFI:

$ sudo ifconfig
dummy0: flags=195<UP,BROADCAST,RUNNING,NOARP> mtu 1500
inet6 fe80::8068:21ff:fe3e:8a83 prefixlen 64 scopeid 0x20
ether 82:68:21:3e:8a:83 txqueuelen 1000 (Ethernet)
RX packets 0 bytes 0 (0.0 B)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 264 bytes 37544 (36.6 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
inet 127.0.0.1 netmask 255.0.0.0
inet6 ::1 prefixlen 128 scopeid 0x10
loop txqueuelen 1 (Local Loopback)
RX packets 209 bytes 15888 (15.5 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 209 bytes 15888 (15.5 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

rmnet_data0: flags=65<UP,RUNNING> mtu 2000
inet6 fe80::147a:255f:22ed:3948 prefixlen 64 scopeid 0x20
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
RX packets 20 bytes 3307 (3.2 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 16 bytes 1179 (1.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

rmnet_ipa0: flags=65<UP,RUNNING> mtu 2000
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
RX packets 10 bytes 3547 (3.4 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 16 bytes 1179 (1.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST> mtu 1500
inet 192.168.0.101 netmask 255.255.255.0 broadcast 192.168.0.255
inet6 fe80::d29c:7aff:feed:2a37 prefixlen 64 scopeid 0x20
ether d0:9c:7a:ed:2a:37 txqueuelen 3000 (Ethernet)
RX packets 728341 bytes 927379046 (884.4 MiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 401774 bytes 31421894 (29.9 MiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

При выключенном WIFI

$ sudo ifconfig
dummy0: flags=195<UP,BROADCAST,RUNNING,NOARP> mtu 1500
inet6 fe80::8068:21ff:fe3e:8a83 prefixlen 64 scopeid 0x20
ether 82:68:21:3e:8a:83 txqueuelen 1000 (Ethernet)
RX packets 0 bytes 0 (0.0 B)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 275 bytes 39074 (38.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING> mtu 65536
inet 127.0.0.1 netmask 255.0.0.0
inet6 ::1 prefixlen 128 scopeid 0x10
loop txqueuelen 1 (Local Loopback)
RX packets 218 bytes 16653 (16.2 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 218 bytes 16653 (16.2 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

rmnet_data0: flags=65<UP,RUNNING> mtu 2000
inet6 fe80::147a:255f:22ed:3948 prefixlen 64 scopeid 0x20
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
RX packets 20 bytes 3307 (3.2 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 16 bytes 1179 (1.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

rmnet_ipa0: flags=65<UP,RUNNING> mtu 2000
unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00 txqueuelen 1000 (UNSPEC)
RX packets 10 bytes 3547 (3.4 KiB)
RX errors 0 dropped 0 overruns 0 frame 0
TX packets 16 bytes 1179 (1.1 KiB)
TX errors 0 dropped 0 overruns 0 carrier 0 collisions 0

**Comment by paradoxx816** [comment]
При отключении wifi в шторке интерфейс wlan0 должен быть. Может попробовать отключить wifi только через термукс (sudo ifconfig wlan0 down)

**Comment by fateev1000** [comment]
> При отключении wifi в шторке интерфейс wlan0 должен быть. Может попробовать отключить wifi только через термукс (sudo ifconfig wlan0 down)

При вводе данной команды происходит отключение от подключенного WIFI, сам WIFI не выключается и в Termux также циклит как и раньше... Вот как происходит [https://youtu.be/Vzaj1Zdmjnk](url)

**Comment by drygdryg** [comment]
Удаление интерфейса Wi-Fi — это известная проблема некоторых прошивок MIUI. Пока что я не нашёл её решения. Воспользуйтесь сторонней прошивкой либо откатитесь до предыдущей версии MIUI.

**Comment by fateev1000** [comment]
> Удаление интерфейса Wi-Fi — это известная проблема некоторых прошивок MIUI. Пока что я не нашёл её решения. Воспользуйтесь сторонней прошивкой либо откатитесь до предыдущей версии MIUI.

Хорошо. Спасибо.
