### ISSUE TITLE
Random MAC with every target

### ISSUE THREAD

**Issue by eda-abec** [drygdryg/OneShot#24]
There could be optional dependency on macchanger and a switch for this.

**Comment by drygdryg** [comment]
This is a good addition to the functionality, but the problem is that macchanger does not work on all devices, some devices (e.g. Andriod devices) require vendor-specific methods for changing the MAC address. For example, MediaTek and Qualcomm Snapdragon: there are many ways to change the MAC address that go beyond the standard Linux tools. So macchanger just won't work here — it requires native tools like Change My MAC, etc.

**Comment by eda-abec** [comment]
Actually, I've tested it with macchanger from Termux repository and it works. I am well aware of problems with MACs on Android and in general, but it still might be a nice feature. Maybe just when there's nothing else to do. :)

**Comment by jevgenyonegin** [comment]
I'm using this function almost found this project (Snapdragon 625), and always using few bash commands like sudo bash "script name":
#!/bin/bash
macchanger -r wlan0
./OneShot/oneshot.py -i wlan0 -K -w
>For default scan "wps".
#!/bin/bash
macchanger -r wlan0
./OneShot/oneshot.py -i wlan0 -K -F -w
>For forced "wpsf".
#!/bin/bash
macchanger -r wlan0
./OneShot/oneshot.py -i wlan0 -B -w
>For bruteforce "wpsb". Just if AP is not locking.
#!/bin/bash
macchanger -r wlan0
./OneShot/oneshot.py -i wlan0 -B -d 61 -w
>For 61 sec delay "wpsd". Supports Technicolor routers and taking lots of time (week if pin is starting on 9999, and less if you can guess first digit to start), but you can continue process at any time.
And final one:
#!/bin/bash
wget https://raw.githubusercontent.com/drygdryg/OneShot/master/oneshot.py
wget https://raw.githubusercontent.com/drygdryg/OneShot/master/vulnwsc.txt
mv -f {oneshot.py,vulnwsc.txt} OneShot/
chmod 766 OneShot/{oneshot.py,vulnwsc.txt}
> Easy way to update this fantastic project "update". Ofcorse you have to install macchanger if device supports.
I'm using long commands just if AP is open, is not vulnerable to pixie, have default access and can show correct pin:
sudo python ./OneShot/oneshot.py -i wlan0 -p "pin" -w
>to keep AP stored as whatever happens:)
