### ISSUE TITLE
AP wsc data

### ISSUE THREAD

**Issue by jevgenyonegin** [drygdryg/OneShot#27]
Can anybody tell me why and how some AP's hidе wsc data? Is it config option or just specific models support? If option, how to find that? Googled - no results.

**Comment by drygdryg** [comment]
Different routers have different WPS implementations. For example, in the Realtek SDK, this is wscd. Therefore, many router firmwares based on the Realtek SDK, has non-unique WSC model, for example, most Netis routers. Unfortunately, I haven't seen any access points that would allow you to change this configuration from the web interface. This configuration is programmed by the firmware developers.

**Comment by jevgenyonegin** [comment]
As example if I see MikroTik or RB952Ui-5ac2nD 0(lots of difference's) I'm just skeeping... They are not volnerable at all... About firmware, yes, possible... Because lots of routers trading mobile operators and they have specific (flashed) firmware.
