### ISSUE TITLE
Don't show "BSSID not specified" when --loop switch active

### ISSUE THREAD

**Issue by eda-abec** [drygdryg/OneShot#28]
The loop mode is supposed for repeating the process, hence it does not make sense to specify the BSSID. So the warning should be silenced in loop mode.

**Comment by jevgenyonegin** [comment]
I think this warning doesn't need to be shown at any time, should be warned if you made mistake... Want more info- welcome to --help;)

**Comment by eda-abec** [comment]
It's the way software evolves and finds its paths...
In some point in history, it may have had sense, but I agree to move it to help.


Or generally speaking, what about some --quiet mode for experienced users? Would also address #29

**Comment by drygdryg** [comment]
Solved in bd16b1c152d92d80ad2343614d3a32d31d786f83
