### ISSUE TITLE
Project new's

### ISSUE THREAD

**Issue by jevgenyonegin** [drygdryg/OneShot#32]
Any information about the developer? I'm starting to worry!;(

**Comment by eda-abec** [comment]
I don't have any, it also worries me. At least the project is in fully usable state...

**Comment by jevgenyonegin** [comment]
I've got good news about this project, no worries, it's alive! At the moment developer collecting ap deep info with https://github.com/drygdryg/wigle_companion project, which will help oneshot project as well. We can meke this faster by walking around with wigle_companion and sending loggs (*.db) to developer.
