### ISSUE TITLE
An possibly interesting resource

### ISSUE THREAD

**Issue by eda-abec** [drygdryg/OneShot#33]
I came across this site by a chance, and although I don't understand it much :D, it looks interesting:

https://tosunkaya.com/araclari/wps-pin-generator-online/

**Comment by jevgenyonegin** [comment]
it doesn't seems to be really serious service, even  if it tries, why it generates pin's offline, why just one pin and where are any bases? Better to use 3WiFi! For 5$ registration you will get access to really huge base of hacked ap, online pin generator (oneshot using offline 3WiFi generator) and nice app router scan (app available for free on win/linux/android).
