### ISSUE TITLE
Flags instead of coloring

### ISSUE THREAD

**Issue by eda-abec** [drygdryg/OneShot#35]
The project is the state, where APs can have too many "states" to simply signalize them by color. So we might add a column "flags" to the scan, which could display multiple states at once.

The exact appearance is a thing of discussion, maybe color fields, letters, or UTF-8 characters?

Suggestions for flags:

-  WPS Locked
- stored
-  vulnerable
--
- PIN already stored (wouldn't be hard to implement)
- unsuccessfully probed within this session

and maybe more :)

**Comment by drygdryg** [comment]
Finally implemented in 436d2c06e874aa3bf2a0a307097d0c74e55b9fef

**Comment by eda-abec** [comment]
Actually, what I meant was something similar to `ls -l` output, with its "flags" for indicating folders etc. 436d2c0 solved #29, which I closed just now.

**Comment by eda-abec** [comment]
Another idea: signalizing open network
