### ISSUE TITLE
Решение проблемы с МТК

### ISSUE THREAD

**Issue by nikita-yfh** [drygdryg/OneShot#44]
Когда я пытаюсь взломать Wifi на смартфоне с mt6761, то не удается:
```
[*] Scanning…
[*] Associating with AP…
[+] Associated with B0:95:75:51:ED:E4 (ESSID: milo$erdovi)
[*] Scanning…
[*] Associating with AP…
[+] Associated with B0:95:75:51:ED:E4 (ESSID: milo$erdovi)
[*] Scanning…
[*] Associating with AP…
[+] Associated with B0:95:75:51:ED:E4 (ESSID: milo$erdovi)
[*] Scanning…
```
......
Решение проблемы
Если полностью убить wpa_supplicant
`while true; do pkill wpa_supplicant; done`
то скрипт работать будет.

Недостатки: wifi не будет работать до перезагруки телефона.

**Comment by ValentineShilov** [comment]
> Решение проблемы
> Если полностью убить wpa_supplicant
> `while true; do pkill wpa_supplicant; done`
> то скрипт работать будет.
> 
> Недостатки: wifi не будет работать до перезагруки телефона.

Спасибо, этот способ работает. У меня на телефоне с mt6771 можно потом починить wifi без перезагрузки телефона, если включить и выключить hotspot, потом включить wifi
....
Fix with killing wpa_supplicant works for mt6771  device. To get wifi working back normally after using oneshot  enable and disable hotspot, then turn on wifi

**Comment by nikita-yfh** [comment]
Нашел другой способ: в настройках геолокации включить поиск сетей, включить геолокацию и отключить wifi

**Comment by mahrabshaon** [comment]
How to kill wpa_supplicant..? My phone is also mt6771 and I'm also facing the same problem.. on my geo location settings scanning is turned on, but isn't working... Help me..

**Comment by mahrabshaon** [comment]
I tried ur method.. but it didn't worked for my mt6771.
Here is the results:
~ $ sudo pkill wpa_supplicant
~ $ sudo python OneShot/oneshot.py -i wlan0 -K
Cannot find device "wlan0"
Unable to up interface "wlan0"
~ $

**Comment by drygdryg** [comment]
Possible solution (first disable Wi-Fi):
```
sudo chmod 644 /dev/wmtWifi
sudo sh -c 'echo 1 > /dev/wmtWifi'
```
On my device, chmodding can be omitted. Tested on MT6580 SoC and seems to work fine!


Возможное решение проблемы (сначала нужно отключить Wi-Fi):
```
sudo chmod 644 /dev/wmtWifi
sudo sh -c 'echo 1 > /dev/wmtWifi'
```
На моём устройстве можно опустить команду chmod. Протестировал на MT6580, и похоже, что это чудесно работает!

**Comment by nikita-yfh** [comment]
It was implemented here: [](https://github.com/nikita-yfh/OneShot-C)

**Comment by drygdryg** [comment]
https://github.com/drygdryg/OneShot#the-wlan0-interface-disappears-when-wi-fi-is-disabled-on-android-devices-with-mediatek-soc
