### ISSUE TITLE
Option to reverse scan order

### ISSUE THREAD

**Issue by eda-abec** [drygdryg/OneShot#45]
It would be nice, especially on smaller Android screens, to sort network scan results in ascending order (strongest signal on bottom). It should take only a few lines and I can write them if we agree on name of the switch - maybe "--reverse-scan / -r"?

**Comment by eda-abec** [comment]
So, I successfully implemented it [here](https://github.com/eda-abec/OneShot/tree/reverse-scan). Would be glad if you pulled it .:smile:

**Comment by drygdryg** [comment]
Sorry, I think I made a mistake when merging. Could you pull and merge current master branch from this repo please?
