### ISSUE TITLE
After canceling a Successfull attack, OneShot Loops

### ISSUE THREAD

**Issue by KikoTs** [drygdryg/OneShot#50]
![Screenshot_20210607_163622.png](https://user-images.githubusercontent.com/46856249/121020652-3bb43b80-c7a9-11eb-9b48-037ad4be3374.png)

Not entirely sure why, it does it frequently, not matter router model or location, loop persists until device is changed.

**Comment by paradoxx816** [comment]
This is usually due to a weak signal. Try to get closer to the router

**Comment by KikoTs** [comment]
> This is usually due to a weak signal. Try to get closer to the router

I can't really confirm, as I was -72dB from the wifi and this error occurred, but when I tried after 1 hour I think I was -75dB away from it, it somehow worked. 🙄

**Comment by jevgenyonegin** [comment]
It's not a script bug but AP's... Changing MAC or retrying a bit later always helps.

**Comment by KikoTs** [comment]
> It's not a script bug but AP's... Changing MAC or retrying a bit later always helps.

You seem to be right, I haven't tested the mac change but it fixes itself after time, therefore its not a script bug as you mentioned.
