### ISSUE TITLE
Notifications?;)

### ISSUE THREAD

**Issue by jevgenyonegin** [drygdryg/OneShot#53]
It may sound crazy, but is it possible to organize sound notification when potentially vulnerable networks are detected, of course, as an option? It's about safety on the way!:D paplay seems to be playing sounds in the terminal, though not all... And if get so far, wold be nice to use continuous scan like radar in the pocket;) I'm just trying to keep this project alive...

**Comment by drygdryg** [comment]
This is a great idea, thanks. But I think it should be left for the Android application which I plan to create.
