### ISSUE TITLE
No WPS networks found, Unable to up interface "wlan0"

### ISSUE THREAD

**Issue by RuslanUC** [drygdryg/OneShot#54]
Если wifi включен, то пишет 
[*] BSSID not specified (--bssid) — scanning for available networks
[-] No WPS networks found.

Но когда я выключаю wifi, то пишет
Cannot find device "wlan0"
Unable to up interface "wlan0"

Android 6, MIUI 10.

**Comment by drygdryg** [comment]
Check if wlan0 interface is avaliable. List available wireless interfaces using `iw dev`

**Comment by RuslanUC** [comment]
No, wlan0 interface is not available.

![Screenshot_2021-07-21-08-40-23-192_com termux](https://user-images.githubusercontent.com/45573310/126437173-c14dce9c-12c1-4630-a628-24609c146d31.png)

**Comment by jevgenyonegin** [comment]
**@RuslanUC** WIFI must be disabled, this function should  perform activated GPS with ** permission ** to search for wireless networks, GPS options available by long press.
I would like a backup of your termux, device appeared on android 6, but it cannot be used easely as repository is no longer available...  Can you please share the archiver using gdrive and script below: 
WIFI должен быть отключен, эту функцию должен выполнять GPS с **разрешением** на поиск беспроводных сетей, опции gps по долгому нажатию.
Хотелось бы бекап вашего termux, появилось тело на андроид 6, а завести не получается, репозиторий не доступны... Не поделитесь архивчиком при помощи гдрайв и скрипта ниже?

```
cd /data/data/com.termux/files
rm -rf home
sudo tar -zxvf /sdcard/termux-backup.tar.gz home usr

**Comment by RuslanUC** [comment]
I enabled gps with search for wireless networks, but it wlan0 still not available. I will send termux backup in a few hours.

У меня включен gps с поиском по wifi, но wlan0 не доступен (когда wifi выключен). Бекап termux кину через несколько часов.

**Comment by drygdryg** [comment]
@RuslanUC it looks like you faced general MediaTek wireless driver issue. This issue is present on MediaTek mobile SoCs, and now I don't know any solutions to it. Perhaps the solution from Nikita will help you: https://github.com/drygdryg/OneShot/issues/44

**Comment by RuslanUC** [comment]
@jevgenyonegin ссылка на бекап термукса:
https://drive.google.com/file/d/1puGPdWrTEZeJnNXjV0mcJLrRW90yosT1/view?usp=drivesdk

**Comment by RuslanUC** [comment]
@drygdryg but my phone on Qualcomm, not MediaTek. Solution from Nikita not working:

Select target (press Enter to refresh): 3
[*] Running wpa_supplicant…

and nothing happens.

**Comment by Rs232k** [comment]
Activate wifi but without connections and try again.

**Comment by RuslanUC** [comment]
Still doesn't work.

**Comment by Rs232k** [comment]
Installed wpa_supplicant?

**Comment by RuslanUC** [comment]
Yes

**Comment by Rs232k** [comment]
Ok, idk
