### ISSUE TITLE
Problem on chromebook

### ISSUE THREAD

**Issue by midozalouk** [drygdryg/OneShot#66]
i have the following weird problem when running the Oneshot script

```
sudo python3 oneshot.py  -i mlan0 -b YNWA -p 12345678
[*] Running wpa_supplicant…
[*] Running wpa_supplicant…
[*] Trying PIN '12345678'…
Traceback (most recent call last):
  File "/home/chronos/user/Downloads/oneshot.py", line 1197, in <module>
    companion.single_connection(args.bssid, args.pin, args.pixie_dust,
  File "/home/chronos/user/Downloads/oneshot.py", line 705, in single_connection
    self.__wps_connection(bssid, pin, pixiemode)
  File "/home/chronos/user/Downloads/oneshot.py", line 658, in __wps_connection
    print(self._explain_wpas_not_ok_status(cmd, r))
TypeError: Companion._explain_wpas_not_ok_status() takes 2 positional arguments but 3 were given
```

it happens with any method either online bruteforce or pixidust 

thanks in advance

**Comment by drygdryg** [comment]
Specifically, this behavior was caused by a bug. I fixed it. Update OneShot (using `git pull`) and try to run it again. In case of an error, write here.

**Comment by midozalouk** [comment]
Select target (press Enter to refresh): 2
[*] Running wpa_supplicant…
[*] Trying PIN '12345670'…
[!] Something went wrong — check out debug log
chronos@localhost /usr/local/OneShot $

**Comment by drygdryg** [comment]
Run OneShot with the `-v` flag.

**Comment by midozalouk** [comment]
chronos@localhost ~/Downloads/OneShot $ sudo python3 oneshot.py -i mlan0 -v
[*] Running wpa_supplicant…
[*] BSSID not specified (--bssid) — scanning for available networks
Network marks: Possibly vulnerable | WPS locked | Already stored
Networks list:
#    BSSID              ESSID                     Sec.     PWR  WSC device name             WSC model
1)   DC:99:14:8D:D0:98  YNWA                      WPA2     -51  HuaweiONT                   Huawei HG8121H
2)   EC:F0:FE:B7:CD:1F  WE_B7CD1F                 WPA/WPA2 -92                               
Select target (press Enter to refresh): 1
[*] Running wpa_supplicant…
[*] Trying PIN '12345670'…
[!] Something went wrong — check out debug log
chronos@localhost ~/Downloads/OneShot $

**Comment by midozalouk** [comment]
Solved when i recompiled wpa_supplicant with wps support
although it doesn't throw up mistakes
