### ISSUE TITLE
Program seems to crash or dont work at all

### ISSUE THREAD

**Issue by RadioactivePlays** [drygdryg/OneShot#68]
After the inicial command `sudo python OneShot/oneshot.py -i wlan0 -K` It only shows "Running wpa_supplicant" forever and nothing else happens.
![Screenshot_20220722-100914](https://user-images.githubusercontent.com/19830027/180457077-2c68b44e-d973-4b4a-aba3-6856253899ad.png)

**Comment by drygdryg** [comment]
Try running the `wpa_supplicant` manually. If it fails, then update the packages:
```
pkg update
```

**Comment by RadioactivePlays** [comment]
> 

It worked, thanks.
