### ISSUE TITLE
Unable to up interface "wlan0"

### ISSUE THREAD

**Issue by HackerSpl0it** [drygdryg/OneShot#70]
This is a Termux error im using preinstalled package "fakeroot" on new Version of Termux and in this tool i found te following error. Please help me. Thanks!
~/OneShot # python3 oneshot.py -i wlan0 -b 00:90:4C:C1:AC:21 -K
/data/data/com.termux/files/usr/bin/sh: 1: ip: not found
Unable to up interface "wlan0"

**Comment by eda-abec** [comment]
It seems you are missing the `ip` binary. If that is the case (run `ip` in shell), try installing either net-tools or iproute2 package.

**Comment by drygdryg** [comment]
You need real root, not fakeroot. Use sudo (`pkg install tsu`) to run OneShot.
