### ISSUE TITLE
Missing openssl dependency

### ISSUE THREAD

**Issue by calandoa** [drygdryg/OneShot#71]
I just tried OneShot on my rooted Samsung S20FE with Terux, and it was blocked at:
`print('[*] Running wpa_supplicant…')`

After investigating a bit, I found that `wpa_supplicant` could not start because libssl.so.3 was missing.

I had to install it with:
`pkg install openssl`

After this, it instantaneously worked with PBC on my router. 

Maybe this could be added to the installer or the doc?

BTW, any idea how to execute it directly from the Android main screen?

**Comment by eda-abec** [comment]
As for the openssl dependency, I am not able to replicate it without screwing my Termux environment, bit it seems fair. You can either make a pull request adding this to readme, or ping drygdryg.

For the executing, I'd recommend two resources:
- Termux widgets: https://wiki.termux.com/wiki/Termux:Widget
- my collection of launchers (from terminal only): https://github.com/eda-abec/Launching-Scripts

However, I've never combined those two together, further research is up to you.

**Comment by eda-abec** [comment]
Could you please mark this issue as solved, if that pull request resolved it? I don't have the rights to do it.
