### ISSUE TITLE
[!] Not enough data to run Pixie Dust attack

### ISSUE THREAD

**Issue by AlterioFarto** [drygdryg/OneShot#78]
[*] Received WPS Message M1
[-] wpa_supplicant returned WPS-FAIL
[!] Not enough data to run Pixie Dust attack

**Comment by k-redas** [comment]
I have de same message but fot the next step

![img](https://user-images.githubusercontent.com/57940928/195285742-460743de-2100-4257-9b82-b84cd2d68a8c.jpg)

**Comment by eda-abec** [comment]
This happens with some router models. Are those you tried OneShot on in the list of [vulnerable devices](https://github.com/drygdryg/OneShot/blob/master/vulnwsc.txt)?
