### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by fateev1000** [drygdryg/OneShot#8]
Через Linux Deploy установил Ubuntu 18.04 

При этой команде всё хорошо. Pixie dust работает.
sudo python3 oneshot.py -i wlan0 -b 00:90:4C:C1:AC:21 -K

При вводе команды: sudo python3 oneshot.py -i wlan0 -K
Вот такая ошибка:
Traceback (most recent call last):
  File "oneshot.py", line 717, in <module>
    print('BSSID not specified (--bssid) \u2014 scanning for av
ailable networks...')
UnicodeEncodeError: 'ascii' codec can't encode character '\u201
4' in position 30: ordinal not in range(128)

Не критично. BSSID определяю через другие приложения, но хотелось бы всё в одном месте.

**Comment by drygdryg** [comment]
Проблема связана с кодировками в Ubuntu 18.04. Попробуйте другой дистрибутив, например, Apline Linux. Пока я не выяснил, как это исправить на Ubuntu 18.04.

The problem is related to encodings in Ubuntu 18.04. Try a different Linux distribution, such as Alpine. So far, I haven't been able to fix it on Ubuntu 18.04.

**Comment by fateev1000** [comment]
Всё теперь работает! А возможно как-то увеличить время поиска сетей? Просто очень быстро сканирует(3-4 секунды) и мало точек определяет. Может определить 1, а может 4. При этом устройство не перемещалось.

**Comment by drygdryg** [comment]
Для сканирования используется бэкенд [iw](https://wireless.wiki.kernel.org/en/users/documentation/iw). OneShot никак не может повлиять на параметры сканирования.
Возможно, обновление списка сетей (повторное сканирование) будет полезно вам. Для того чтобы пересканировать сети, вместо номера сети введите `r` и нажмите Enter.

**Comment by fateev1000** [comment]
> Для сканирования используется бэкенд [iw](https://wireless.wiki.kernel.org/en/users/documentation/iw). OneShot никак не может повлиять на параметры сканирования.
> Возможно, обновление списка сетей (повторное сканирование) будет полезно вам. Для того чтобы пересканировать сети, вместо номера сети введите `r` и нажмите Enter.

**Comment by fateev1000** [comment]
Благодарю. Больше вопросов нет.

**Comment by fateev1000** [comment]
Еще есть вопрос. А почему некоторые сети выделены красным цветом?

**Comment by fateev1000** [comment]
Как принудительно остановить работу скрипта, если долго пытается подключится?

**Comment by drygdryg** [comment]
Красным цветом выделяются сети с заблокированным WPS.
Работу скрипта можно остановить сочетанием клавиш Ctrl + C (процессу посылается сигнал SIGINT).
