### ISSUE TITLE
AttributeError: module 'os' has no attribute 'getuid'.

### ISSUE THREAD

**Issue by Himanshumm** [drygdryg/OneShot#90]
It says  this after entering the arguments

Traceback (most recent call last):
  File "C:/Program Files/Python311/hack.py", line 1185, in <module>
    if os.getuid() != 0:
AttributeError: module 'os' has no attribute 'getuid'. Did you mean: 'getpid'?
What should i do

**Comment by drygdryg** [comment]
OneShot does not support Windows OS.
